/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TestPack;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author NGOC THUC
 */
public class testFrame extends javax.swing.JFrame {

    ArrayList<JLabel> listItems = new ArrayList<>();

    /**
     * Creates new form testFrame
     */
    public testFrame() {

        initComponents();
        designComp();

    }

    void designComp() {
        spnMenu.getVerticalScrollBar().setUnitIncrement(16);

        createListItems();
        solveActionMenu();
    }

    void createListItems() {
        listItems.add(lblBanHang);
        listItems.add(lblNhapHang);
        listItems.add(lblSanPham);
        listItems.add(lblHoaDon);
        listItems.add(lblPhieuNhap);
        listItems.add(lblNhanVien);
        listItems.add(lblCongTy);
        listItems.add(lblThongKe);
        listItems.add(lblTaiKhoan);
        listItems.add(lblPhanQuyen);
    }

    void solveActionMenu() {
        lblBanHang.addMouseListener(new handleMouseEvent(pnContent, pnBanHang));
        lblNhapHang.addMouseListener(new handleMouseEvent(pnContent, pnNhapHang));
        lblSanPham.addMouseListener(new handleMouseEvent(pnContent, pnSanPham));
        lblHoaDon.addMouseListener(new handleMouseEvent(pnContent, pnHoaDon));
        lblPhieuNhap.addMouseListener(new handleMouseEvent(pnContent, pnPhieuNhap));
        lblNhanVien.addMouseListener(new handleMouseEvent(pnContent, pnNhanVien));
        lblCongTy.addMouseListener(new handleMouseEvent(pnContent, pnCongTy));
        lblTaiKhoan.addMouseListener(new handleMouseEvent(pnContent, pnTaiKhoan));
        lblPhanQuyen.addMouseListener(new handleMouseEvent(pnContent, pnPhanQuyen));
        lblThongKe.addMouseListener(new handleMouseEvent(pnContent, pnThongKe));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContainer = new javax.swing.JPanel();
        pnSideBar = new javax.swing.JPanel();
        pnLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        spnMenu = new javax.swing.JScrollPane();
        pnListItem = new javax.swing.JPanel();
        lblSanPham = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        lblNhapHang = new javax.swing.JLabel();
        lblCongTy = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblPhieuNhap = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblPhanQuyen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();
        pnSanPham = new javax.swing.JPanel();
        pnBanHang = new javax.swing.JPanel();
        pnNhapHang = new javax.swing.JPanel();
        pnCongTy = new javax.swing.JPanel();
        pnNhanVien = new javax.swing.JPanel();
        pnHoaDon = new javax.swing.JPanel();
        pnPhieuNhap = new javax.swing.JPanel();
        pnThongKe = new javax.swing.JPanel();
        pnTaiKhoan = new javax.swing.JPanel();
        pnPhanQuyen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pnContainer.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnSideBar.setBackground(new java.awt.Color(135, 172, 217));
        pnSideBar.setPreferredSize(new java.awt.Dimension(260, 720));

        pnLogo.setBackground(new java.awt.Color(135, 172, 217));
        pnLogo.setPreferredSize(new java.awt.Dimension(260, 120));

        jLabel1.setBackground(new java.awt.Color(135, 172, 217));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 243, 244));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\logo\\main_logo.png")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 100));
        pnLogo.add(jLabel1);

        jSeparator1.setBackground(new java.awt.Color(243, 243, 244));
        jSeparator1.setForeground(new java.awt.Color(243, 243, 244));
        jSeparator1.setPreferredSize(new java.awt.Dimension(250, 10));
        pnLogo.add(jSeparator1);

        spnMenu.setBorder(null);
        spnMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spnMenu.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        spnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spnMenu.setMaximumSize(new java.awt.Dimension(260, 550));
        spnMenu.setPreferredSize(new java.awt.Dimension(260, 1050));
        spnMenu.setRequestFocusEnabled(false);

        pnListItem.setBackground(new java.awt.Color(135, 172, 217));
        pnListItem.setAutoscrolls(true);
        pnListItem.setPreferredSize(new java.awt.Dimension(260, 850));

        lblSanPham.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(243, 243, 244));
        lblSanPham.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblSanPham.setText("SẢN PHẨM");
        lblSanPham.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblSanPham);

        lblBanHang.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblBanHang.setForeground(new java.awt.Color(243, 243, 244));
        lblBanHang.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblBanHang.setText("BÁN HÀNG");
        lblBanHang.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblBanHang);

        lblNhapHang.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblNhapHang.setForeground(new java.awt.Color(243, 243, 244));
        lblNhapHang.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblNhapHang.setText("NHẬP HÀNG");
        lblNhapHang.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblNhapHang);

        lblCongTy.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCongTy.setForeground(new java.awt.Color(243, 243, 244));
        lblCongTy.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblCongTy.setText("CÔNG TY SÁCH");
        lblCongTy.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblCongTy);

        lblNhanVien.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(243, 243, 244));
        lblNhanVien.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblNhanVien.setText("NHÂN VIÊN");
        lblNhanVien.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblNhanVien);

        lblHoaDon.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(243, 243, 244));
        lblHoaDon.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblHoaDon.setText("HÓA ĐƠN");
        lblHoaDon.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblHoaDon);

        lblPhieuNhap.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblPhieuNhap.setForeground(new java.awt.Color(243, 243, 244));
        lblPhieuNhap.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblPhieuNhap.setText("PHIẾU NHẬP");
        lblPhieuNhap.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblPhieuNhap);

        lblThongKe.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(243, 243, 244));
        lblThongKe.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblThongKe.setText("THỐNG KÊ");
        lblThongKe.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblThongKe);

        lblTaiKhoan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(243, 243, 244));
        lblTaiKhoan.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblTaiKhoan.setText("TÀI KHOẢN");
        lblTaiKhoan.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblTaiKhoan);

        lblPhanQuyen.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblPhanQuyen.setForeground(new java.awt.Color(243, 243, 244));
        lblPhanQuyen.setIcon(new javax.swing.ImageIcon("D:\\Y3_S1\\Software_Engineering\\access\\icon_40px\\product_2.png")); // NOI18N
        lblPhanQuyen.setText("PHÂN QUYỀN");
        lblPhanQuyen.setPreferredSize(new java.awt.Dimension(260, 80));
        pnListItem.add(lblPhanQuyen);

        spnMenu.setViewportView(pnListItem);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnSideBarLayout = new javax.swing.GroupLayout(pnSideBar);
        pnSideBar.setLayout(pnSideBarLayout);
        pnSideBarLayout.setHorizontalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSideBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
            .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnSideBarLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(spnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        pnSideBarLayout.setVerticalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addComponent(pnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 520, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSideBarLayout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(spnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGap(80, 80, 80)))
        );

        pnContainer.add(pnSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnContent.setLayout(new java.awt.CardLayout());

        pnSanPham.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnSanPham, "card2");

        pnBanHang.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout pnBanHangLayout = new javax.swing.GroupLayout(pnBanHang);
        pnBanHang.setLayout(pnBanHangLayout);
        pnBanHangLayout.setHorizontalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnBanHangLayout.setVerticalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnBanHang, "card3");

        pnNhapHang.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout pnNhapHangLayout = new javax.swing.GroupLayout(pnNhapHang);
        pnNhapHang.setLayout(pnNhapHangLayout);
        pnNhapHangLayout.setHorizontalGroup(
            pnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnNhapHangLayout.setVerticalGroup(
            pnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnNhapHang, "card4");

        pnCongTy.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout pnCongTyLayout = new javax.swing.GroupLayout(pnCongTy);
        pnCongTy.setLayout(pnCongTyLayout);
        pnCongTyLayout.setHorizontalGroup(
            pnCongTyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnCongTyLayout.setVerticalGroup(
            pnCongTyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnCongTy, "card5");

        pnNhanVien.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnNhanVien, "card6");

        pnHoaDon.setBackground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout pnHoaDonLayout = new javax.swing.GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnHoaDon, "card7");

        pnPhieuNhap.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout pnPhieuNhapLayout = new javax.swing.GroupLayout(pnPhieuNhap);
        pnPhieuNhap.setLayout(pnPhieuNhapLayout);
        pnPhieuNhapLayout.setHorizontalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnPhieuNhapLayout.setVerticalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnPhieuNhap, "card8");

        pnThongKe.setBackground(new java.awt.Color(102, 153, 0));

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnThongKe, "card9");

        pnTaiKhoan.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnTaiKhoanLayout = new javax.swing.GroupLayout(pnTaiKhoan);
        pnTaiKhoan.setLayout(pnTaiKhoanLayout);
        pnTaiKhoanLayout.setHorizontalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnTaiKhoanLayout.setVerticalGroup(
            pnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnTaiKhoan, "card10");

        pnPhanQuyen.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout pnPhanQuyenLayout = new javax.swing.GroupLayout(pnPhanQuyen);
        pnPhanQuyen.setLayout(pnPhanQuyenLayout);
        pnPhanQuyenLayout.setHorizontalGroup(
            pnPhanQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnPhanQuyenLayout.setVerticalGroup(
            pnPhanQuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pnContent.add(pnPhanQuyen, "card11");

        pnContainer.add(pnContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1020, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException
                | UnsupportedLookAndFeelException e) {

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblCongTy;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblNhapHang;
    private javax.swing.JLabel lblPhanQuyen;
    private javax.swing.JLabel lblPhieuNhap;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JPanel pnBanHang;
    private javax.swing.JPanel pnCongTy;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnListItem;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnNhapHang;
    private javax.swing.JPanel pnPhanQuyen;
    private javax.swing.JPanel pnPhieuNhap;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JPanel pnSideBar;
    private javax.swing.JPanel pnTaiKhoan;
    private javax.swing.JPanel pnThongKe;
    private javax.swing.JScrollPane spnMenu;
    // End of variables declaration//GEN-END:variables

}
